from __future__ import annotations

ADVANCED_STAGE_WORKFLOW_PROFILES: dict[str, dict] = {
    "controlled_resources": {
        "branches": [
            {
                "slug": "biological_inputs",
                "title_en": "Biological input and crop support",
                "title_ru": "Биологические входы и поддержка культур",
                "assemblies": ["kubejs:culture_support_matrix"],
                "target": "mysticalagriculture:infusion_altar",
                "focus_en": "legal first seeds, essence supply, farmland or support conditions, altar input ownership and recovery from an interrupted infusion",
                "focus_ru": "честные первые семена, снабжение эссенцией, условия почвы или поддержки, владение входами алтаря и восстановление прерванной инфузии",
            },
            {
                "slug": "resource_simulation",
                "title_en": "Post-discovery resource simulation",
                "title_ru": "Симуляция ресурсов после открытия",
                "assemblies": ["kubejs:simulation_data_coupler"],
                "target": "hostilenetworks:sim_chamber",
                "focus_en": "first-kill evidence, data-model ownership, prediction cost, protected boss-drop blacklist and prevention of self-funding simulation loops",
                "focus_ru": "доказательство первой победы, владение моделью данных, стоимость предсказания, чёрный список боссового лута и защиту от самоподдерживающегося цикла симуляции",
            },
            {
                "slug": "renewable_harvesting",
                "title_en": "Renewable harvest control",
                "title_ru": "Управление возобновляемым сбором",
                "assemblies": ["kubejs:renewable_harvest_controller"],
                "target": "industrialforegoing:plant_gatherer",
                "depends_on": ["biological_inputs"],
                "focus_en": "working area, seed return, replant ownership, fertilizer demand, output separation and shutdown before voiding rare crops",
                "focus_ru": "рабочую область, возврат семян, владение пересадкой, расход удобрения, разделение выходов и остановку до уничтожения редких культур",
            },
        ],
        "integration_item": "kubejs:bioindustrial_matrix",
        "optimization_en": "renewable yield, prediction cost, crop-cycle time, entity or machine idle work, protected-output rules and recovery after unloading the farm",
        "optimization_ru": "возобновляемый выход, стоимость предсказаний, время цикла культур, работу существ или машин в простое, правила защищённых выходов и восстановление после выгрузки фермы",
    },
    "applied_logistics": {
        "branches": [
            {
                "slug": "controller_network",
                "title_en": "Controller-scale channel network",
                "title_ru": "Канальная сеть с контроллером",
                "assemblies": ["kubejs:controller_channel_frame"],
                "target": "ae2:controller",
                "focus_en": "controller shape, power reserve, channel topology, dense-cable handoff and isolation of a saturated network face",
                "focus_ru": "форму контроллера, резерв энергии, топологию каналов, переход на плотный кабель и изоляцию насыщенной стороны сети",
            },
            {
                "slug": "autocrafting_cpu",
                "title_en": "Autocrafting CPU scheduling",
                "title_ru": "Планирование CPU автокрафта",
                "assemblies": ["kubejs:crafting_cpu_scheduler"],
                "target": "ae2:crafting_unit",
                "depends_on": ["controller_network"],
                "focus_en": "CPU capacity, co-processor parallelism, pattern ownership, missing-input visibility and cancellation without losing supplied materials",
                "focus_ru": "ёмкость CPU, параллелизм сопроцессоров, владение шаблонами, видимость отсутствующего входа и отмену без потери поданных материалов",
            },
            {
                "slug": "quantum_link",
                "title_en": "Cross-dimensional quantum link",
                "title_ru": "Межпространственная квантовая связь",
                "assemblies": ["kubejs:quantum_link_stabilizer"],
                "target": "ae2:quantum_ring",
                "depends_on": ["controller_network"],
                "focus_en": "paired endpoints, remote energy, chunk ownership, one-sided disconnect behaviour and recovery without duplicating stored items",
                "focus_ru": "парные узлы, удалённую энергию, владение чанками, поведение при одностороннем разрыве и восстановление без копирования хранимых предметов",
            },
        ],
        "integration_item": "kubejs:quantum_logic",
        "optimization_en": "channel reserve, crafting request latency, CPU occupancy, subnet isolation, remote power loss and recovery after reloading one endpoint",
        "optimization_ru": "резерв каналов, задержку запроса, занятость CPU, изоляцию подсетей, потерю удалённого питания и восстановление после загрузки одного узла",
    },
    "resonant_energy": {
        "branches": [
            {
                "slug": "nitro_generation",
                "title_en": "Nitro energizing regulation",
                "title_ru": "Регулирование нитро-энергизации",
                "assemblies": ["kubejs:nitro_regulation_array"],
                "target": "powah:energizing_rod_nitro",
                "focus_en": "orb isolation, rod count, transfer rate, recipe energy, input filtering and safe shutdown when the energizing output is blocked",
                "focus_ru": "изоляцию сферы, число стержней, скорость передачи, энергию рецепта, фильтрацию входа и безопасную остановку при полном выходе",
            },
            {
                "slug": "mass_storage",
                "title_en": "Induction Matrix transfer path",
                "title_ru": "Путь передачи Induction Matrix",
                "assemblies": ["kubejs:induction_transfer_manifold"],
                "target": "mekanism:induction_casing",
                "focus_en": "valid casing, provider and cell balance, input-output port separation, usable reserve and safe expansion without disconnecting the factory",
                "focus_ru": "валидный корпус, баланс провайдеров и ячеек, разделение портов, полезный резерв и безопасное расширение без отключения фабрики",
            },
            {
                "slug": "high_current_distribution",
                "title_en": "Resonant high-current distribution",
                "title_ru": "Резонансное распределение высокой мощности",
                "assemblies": ["kubejs:resonant_distribution_frame"],
                "target": "kubejs:resonant_power_cell",
                "depends_on": ["nitro_generation", "mass_storage"],
                "focus_en": "trunk throughput, surge reserve, branch protection, load shedding and recovery after losing one generator or transfer path",
                "focus_ru": "пропускную способность магистрали, резерв по скачку, защиту ветвей, сброс нагрузки и восстановление после потери генератора или пути передачи",
            },
        ],
        "integration_item": "kubejs:resonant_core",
        "optimization_en": "sustained generation, energizing duty cycle, provider transfer rate, reserve duration, idle wireless loads and black-start after total power loss",
        "optimization_ru": "устойчивую генерацию, цикл энергизации, скорость провайдеров, длительность резерва, беспроводные нагрузки в простое и холодный запуск после полного обесточивания",
    },
    "nuclear_antimatter": {
        "branches": [
            {
                "slug": "radiation_containment",
                "title_en": "Radiation interlocks and SPS structure",
                "title_ru": "Радиационные блокировки и структура SPS",
                "assemblies": ["kubejs:radiation_interlock_module"],
                "target": "mekanism:sps_casing",
                "focus_en": "polonium ownership, radiation boundary, structure validity, emergency isolation and recovery without carrying contaminated material through the base",
                "focus_ru": "владение полонием, радиационную границу, валидность структуры, аварийную изоляцию и восстановление без переноса загрязнённого материала через базу",
            },
            {
                "slug": "sps_power_pulse",
                "title_en": "SPS pulse and coil control",
                "title_ru": "Управление импульсом и катушкой SPS",
                "assemblies": ["kubejs:sps_pulse_controller"],
                "target": "mekanism:supercharged_coil",
                "depends_on": ["radiation_containment"],
                "focus_en": "pulse energy, coil count, transfer reserve, controlled enable signal and safe stop after power interruption",
                "focus_ru": "энергию импульса, число катушек, резерв передачи, управляемый сигнал включения и безопасную остановку после прерывания питания",
            },
            {
                "slug": "antimatter_containment",
                "title_en": "Antimatter production and containment",
                "title_ru": "Производство и сдерживание антиматерии",
                "assemblies": ["kubejs:antimatter_containment_cell"],
                "target": "mekanism:pellet_antimatter",
                "depends_on": ["radiation_containment", "sps_power_pulse"],
                "focus_en": "polonium input, energy per pellet, output buffer, prohibition of simulated antimatter and recovery from a full containment output",
                "focus_ru": "вход полония, энергию на гранулу, выходной буфер, запрет симулированной антиматерии и восстановление при полном выходе сдерживания",
            },
        ],
        "integration_item": "kubejs:antimatter_regulator",
        "optimization_en": "radiation exposure boundary, polonium reserve, SPS pulse efficiency, antimatter rate, idle reactor support and restart after an emergency stop",
        "optimization_ru": "границу радиационного воздействия, резерв полония, эффективность импульса SPS, скорость антиматерии, поддержку реактора в простое и перезапуск после аварийной остановки",
    },
}
