from __future__ import annotations

LATE_STAGE_WORKFLOW_PROFILES: dict[str, dict] = {
    "dimensional_materials": {
        "branches": [
            {
                "slug": "expedition_logistics",
                "title_en": "Recoverable expedition logistics",
                "title_ru": "Восстанавливаемая экспедиционная логистика",
                "assemblies": ["kubejs:expedition_supply_frame"],
                "target": "minecraft:shulker_box",
                "focus_en": "labelled cargo, return reserve, protected tools, remote food and energy, retreat criteria and recovery after losing one supply cache",
                "focus_ru": "подписанный груз, резерв возвращения, защищённые инструменты, удалённые запасы еды и энергии, критерии отступления и восстановление после потери одного склада",
            },
            {
                "slug": "trophy_assay",
                "title_en": "Trophy assay and permission evidence",
                "title_ru": "Анализ трофеев и доказательство допуска",
                "assemblies": ["kubejs:trophy_assay_module"],
                "target": "divinerpg:dungeon_tokens",
                "focus_en": "first-victory evidence, ordinary-versus-unique drop classification, assay repeatability, protected storage and rejection of simulated boss proof",
                "focus_ru": "доказательство первой победы, классификацию обычного и уникального лута, повторяемость анализа, защищённое хранение и запрет симулированного доказательства босса",
            },
            {
                "slug": "dimensional_cargo",
                "title_en": "Cross-dimensional cargo anchoring",
                "title_ru": "Якорение межпространственного груза",
                "assemblies": ["kubejs:dimensional_cargo_anchor"],
                "target": "ae2:quantum_ring",
                "depends_on": ["expedition_logistics", "trophy_assay"],
                "focus_en": "link ownership, remote power, one-sided link failure, cargo reconciliation, return-path independence and prevention of duplicated trophies",
                "focus_ru": "владение связью, удалённое питание, отказ одной стороны, сверку груза, независимость обратного пути и защиту от копирования трофеев",
            },
        ],
        "integration_item": "kubejs:dimensional_resonator",
        "optimization_en": "travel preparation time, cargo density, remote-link power, retreat margin, trophy reconciliation and recovery after an unloaded destination",
        "optimization_ru": "время подготовки поездки, плотность груза, питание удалённой связи, запас для отступления, сверку трофеев и восстановление после выгрузки измерения",
    },
    "draconic_engineering": {
        "branches": [
            {
                "slug": "injector_alignment",
                "title_en": "Fusion injector alignment",
                "title_ru": "Юстировка инжекторов слияния",
                "assemblies": ["kubejs:injector_alignment_core"],
                "target": "draconicevolution:wyvern_core",
                "focus_en": "injector count and spacing, exact ingredient ownership, energy symmetry, returned permissions and recovery after an interrupted fusion cycle",
                "focus_ru": "число и расстояние инжекторов, точное владение ингредиентами, симметрию энергии, возврат допусков и восстановление после прерывания цикла слияния",
            },
            {
                "slug": "awakened_containment",
                "title_en": "Awakened material containment",
                "title_ru": "Сдерживание пробуждённых материалов",
                "assemblies": ["kubejs:awakened_containment_shell"],
                "target": "draconicevolution:awakened_core",
                "focus_en": "awakened material ancestry, injector heat and energy reserve, containment boundary, spare-shell policy and safe rejection of an invalid batch",
                "focus_ru": "происхождение пробуждённых материалов, резерв энергии инжекторов, границу сдерживания, запас оболочек и безопасный отказ неверной партии",
            },
            {
                "slug": "draconic_power_interface",
                "title_en": "Draconic power interface",
                "title_ru": "Драконический энергетический интерфейс",
                "assemblies": ["kubejs:draconic_energy_coupler"],
                "target": "mekanism:ultimate_control_circuit",
                "depends_on": ["injector_alignment", "awakened_containment"],
                "focus_en": "high-current transfer, reserve isolation, controlled charge rate, visible saturation and shutdown without voiding awakened components",
                "focus_ru": "передачу большой мощности, изоляцию резерва, управляемую скорость заряда, видимое насыщение и остановку без уничтожения пробуждённых компонентов",
            },
        ],
        "integration_item": "kubejs:draconic_processor",
        "optimization_en": "injector duty cycle, energy symmetry, awakened-material yield, containment reserve, replacement time and restart after a failed fusion injection",
        "optimization_ru": "рабочий цикл инжекторов, симметрию энергии, выход пробуждённого материала, резерв сдерживания, время замены и перезапуск после неудачного слияния",
    },
    "contained_transmutation": {
        "branches": [
            {
                "slug": "emc_accounting",
                "title_en": "EMC accounting and conservation",
                "title_ru": "Учёт и сохранение EMC",
                "assemblies": ["kubejs:emc_accounting_ledger"],
                "target": "projecte:philosophers_stone",
                "focus_en": "source EMC, sink EMC, zero-value gated items, learned-item allowlist, conversion loss and proof that no positive loop exists",
                "focus_ru": "источник и расход EMC, нулевую стоимость закрытых предметов, белый список изучения, потери преобразования и доказательство отсутствия положительного цикла",
            },
            {
                "slug": "matter_compression",
                "title_en": "Matter compression infrastructure",
                "title_ru": "Инфраструктура сжатия материи",
                "assemblies": ["kubejs:matter_compression_frame"],
                "target": "projecte:dark_matter_block",
                "focus_en": "matter-tier ancestry, batch input accounting, compression throughput, overflow storage and replacement of one failed compression module",
                "focus_ru": "происхождение уровней материи, учёт входов партии, скорость сжатия, хранение переполнения и замену одного отказавшего модуля",
            },
            {
                "slug": "transmutation_interlock",
                "title_en": "Transmutation access interlock",
                "title_ru": "Блокировка доступа к трансмутации",
                "assemblies": ["kubejs:transmutation_safety_lock"],
                "target": "projecte:transmutation_table",
                "depends_on": ["emc_accounting", "matter_compression"],
                "focus_en": "access ownership, protected reserves, learned-item policy, automation boundary and safe shutdown when accounting disagrees with inventory",
                "focus_ru": "владение доступом, защищённые резервы, правила изучения предметов, границу автоматизации и безопасную остановку при расхождении учёта и инвентаря",
            },
        ],
        "integration_item": "kubejs:transmutation_matrix",
        "optimization_en": "EMC throughput, accounting latency, matter compression rate, protected reserve, idle collectors and restart after a table or network reload",
        "optimization_ru": "скорость EMC, задержку учёта, скорость сжатия материи, защищённый резерв, простаивающие генераторы и перезапуск после загрузки стола или сети",
    },
    "extreme_fabrication": {
        "branches": [
            {
                "slug": "singularity_routing",
                "title_en": "Singularity routing and inventory control",
                "title_ru": "Маршрутизация сингулярностей и контроль запасов",
                "assemblies": ["kubejs:singularity_routing_lattice"],
                "target": "extendedcrafting:ultimate_singularity",
                "focus_en": "legal source per singularity, exact stock counts, route isolation, missing-input visibility and prevention of circular EMC or simulation supply",
                "focus_ru": "честный источник каждой сингулярности, точные запасы, изоляцию маршрутов, видимость отсутствующего входа и запрет циклического снабжения через EMC или симуляцию",
            },
            {
                "slug": "ultimate_patterns",
                "title_en": "Ultimate pattern infrastructure",
                "title_ru": "Инфраструктура предельных шаблонов",
                "assemblies": ["kubejs:ultimate_pattern_frame"],
                "target": "extendedcrafting:ultimate_table",
                "focus_en": "large-grid recipe ownership, exact pattern version, reusable catalyst handling, blocked-output behavior and recovery after cancelling a long request",
                "focus_ru": "владение крупноматричным рецептом, точную версию шаблона, возврат катализатора, поведение при полном выходе и восстановление после отмены длинного запроса",
            },
            {
                "slug": "bulk_material_flow",
                "title_en": "Bulk material manifold",
                "title_ru": "Магистраль массовых материалов",
                "assemblies": ["kubejs:bulk_material_manifold"],
                "target": "avaritia:extreme_crafting_table",
                "depends_on": ["singularity_routing", "ultimate_patterns"],
                "focus_en": "bulk count accuracy, parallel request boundaries, buffer sizing, slowest-source visibility and safe pause without losing rare components",
                "focus_ru": "точность массовых количеств, границы параллельных запросов, размер буферов, видимость самого медленного источника и безопасную паузу без потери редких компонентов",
            },
        ],
        "integration_item": "kubejs:cosmic_catalyst",
        "optimization_en": "singularity replenishment, pattern request latency, bulk buffer occupancy, parallel table count, idle storage and restart after cancelling or reloading a large craft",
        "optimization_ru": "пополнение сингулярностей, задержку шаблона, заполнение массового буфера, число параллельных столов, простаивающее хранение и перезапуск после отмены или загрузки крупного крафта",
    },
    "cosmic_synthesis": {
        "branches": [
            {
                "slug": "stellar_sampling",
                "title_en": "Stellar sample containment",
                "title_ru": "Сдерживание звёздных образцов",
                "assemblies": ["kubejs:stellar_sample_chamber"],
                "target": "minecraft:end_crystal",
                "focus_en": "sample origin, dimensional cargo reconciliation, containment reserve, duplicate-sample rejection and recovery after an interrupted return trip",
                "focus_ru": "происхождение образца, сверку межпространственного груза, резерв сдерживания, отказ дубликатов и восстановление после прерванного возвращения",
            },
            {
                "slug": "infinity_alloy",
                "title_en": "Infinity alloy crucible",
                "title_ru": "Тигель сплава Бесконечности",
                "assemblies": ["kubejs:infinity_alloy_crucible"],
                "target": "avaritia:infinity_ingot",
                "focus_en": "Infinity material ancestry, crucible batch control, catalyst return, energy reserve and quarantine of an incomplete cosmic alloy batch",
                "focus_ru": "происхождение материалов Бесконечности, управление партией тигля, возврат катализатора, энергетический резерв и карантин неполной космической партии",
            },
            {
                "slug": "cosmic_energy",
                "title_en": "Cosmic energy coupling",
                "title_ru": "Связь космической энергии",
                "assemblies": ["kubejs:cosmic_energy_coupler"],
                "target": "draconicevolution:awakened_core",
                "depends_on": ["stellar_sampling", "infinity_alloy"],
                "focus_en": "multi-system energy ownership, surge isolation, synchronized enable state, visible reserve and safe shutdown of only the cosmic synthesis module",
                "focus_ru": "владение энергией нескольких систем, изоляцию скачков, синхронное включение, видимый резерв и безопасную остановку только модуля космического синтеза",
            },
        ],
        "integration_item": "kubejs:cosmic_synthesis_core",
        "optimization_en": "stellar cargo turnaround, Infinity batch cost, cosmic surge margin, catalyst return time, slowest-domain throughput and restart after an interrupted synthesis cycle",
        "optimization_ru": "оборот звёздного груза, стоимость партии Бесконечности, запас по космическому скачку, время возврата катализатора, скорость самого медленного направления и перезапуск прерванного синтеза",
    },
    "creative_convergence": {
        "branches": [
            {
                "slug": "creative_permissions",
                "title_en": "Creative subsystem permissions",
                "title_ru": "Допуски творческих подсистем",
                "assemblies": ["kubejs:creative_subsystem_key"],
                "target": "kubejs:cosmic_synthesis_core",
                "focus_en": "which limit is removed, prerequisite proof, ownership, irreversible effects and prevention of the key becoming a repeat-consumed tax",
                "focus_ru": "какое ограничение снимается, доказательство предпосылок, владение, необратимые эффекты и запрет превращения ключа в повторный расходный налог",
            },
            {
                "slug": "infinite_logistics",
                "title_en": "Infinite logistics boundary",
                "title_ru": "Граница бесконечной логистики",
                "assemblies": ["kubejs:infinite_logistics_frame"],
                "target": "ae2:controller",
                "focus_en": "network ownership, infinite-capacity boundaries, protected-item exclusion, request visibility and recovery after one remote link fails",
                "focus_ru": "владение сетью, границы бесконечной ёмкости, исключение защищённых предметов, видимость запросов и восстановление после отказа одной удалённой связи",
            },
            {
                "slug": "completion_audit",
                "title_en": "Pack completion audit",
                "title_ru": "Аудит завершения сборки",
                "assemblies": ["kubejs:completion_audit_seal"],
                "target": "kubejs:cosmic_assembly_matrix",
                "depends_on": ["creative_permissions", "infinite_logistics"],
                "focus_en": "all stage proofs, authoritative recipes, anti-bypass state, measured factory capacity, controlled failure and a clean restart before final convergence",
                "focus_ru": "доказательства всех этапов, авторитетные рецепты, состояние антиобходов, измеренную мощность фабрики, контролируемый отказ и чистый перезапуск перед финальной конвергенцией",
            },
        ],
        "integration_item": "kubejs:creative_convergence_matrix",
        "optimization_en": "global request latency, protected-item filtering, idle creative subsystems, cross-dimensional link load, recovery time and post-restart completion consistency",
        "optimization_ru": "задержку глобальных запросов, фильтрацию защищённых предметов, простаивающие творческие подсистемы, нагрузку межпространственных связей, время восстановления и целостность завершения после перезапуска",
    },
}
