from __future__ import annotations

MID_STAGE_WORKFLOW_PROFILES: dict[str, dict] = {
    "precision_manufacturing": {
        "branches": [
            {
                "slug": "compressed_frame",
                "title_en": "Compressed structural fabrication",
                "title_ru": "Производство усиленной конструкции",
                "assemblies": ["kubejs:pressure_treated_frame"],
                "target": "pneumaticcraft:pressure_chamber_valve",
                "focus_en": "compressed-metal supply, frame alignment, pressure-safe joints and replacement of one damaged structural section",
                "focus_ru": "снабжение сжатым металлом, выравнивание рамы, герметичные соединения и замену одного повреждённого конструкционного участка",
            },
            {
                "slug": "substrate_calibration",
                "title_en": "Calibrated substrate line",
                "title_ru": "Линия калиброванных подложек",
                "assemblies": ["kubejs:etched_copper_substrate"],
                "target": "kubejs:calibrated_substrate",
                "focus_en": "etching consistency, conductive-path inspection, component orientation and quarantine of an invalid substrate",
                "focus_ru": "стабильность травления, проверку проводящих дорожек, ориентацию компонентов и карантин неверной подложки",
            },
            {
                "slug": "precision_alignment",
                "title_en": "Precision alignment and PCB assembly",
                "title_ru": "Точная юстировка и сборка плат",
                "assemblies": ["kubejs:assembly_alignment_jig"],
                "target": "pneumaticcraft:printed_circuit_board",
                "depends_on": ["substrate_calibration"],
                "focus_en": "fixture repeatability, component placement, pressure-chamber support, returned tooling and rejection of misaligned boards",
                "focus_ru": "повторяемость оснастки, размещение компонентов, поддержку камеры давления, возврат инструментов и отбраковку смещённых плат",
            },
        ],
        "integration_item": "kubejs:industrial_frame",
        "optimization_en": "compressed-material throughput, substrate defect rate, PCB batch time, tooling travel, spare-frame reserve and blocked-output recovery",
        "optimization_ru": "скорость сжатых материалов, долю брака подложек, время партии PCB, перемещения оснастки, резерв рам и восстановление при полном выходе",
    },
    "digital_storage": {
        "branches": [
            {
                "slug": "processor_manufacturing",
                "title_en": "Processor press infrastructure",
                "title_ru": "Инфраструктура прессования процессоров",
                "assemblies": ["kubejs:processor_press_frame"],
                "target": "ae2:inscriber",
                "focus_en": "press ownership, input isolation, processor sequencing, returned presses and recovery after a blocked processor output",
                "focus_ru": "владение прессами, изоляцию входов, последовательность процессоров, возврат прессов и восстановление при полном выходе",
            },
            {
                "slug": "storage_infrastructure",
                "title_en": "Storage-cell infrastructure",
                "title_ru": "Инфраструктура ячеек хранения",
                "assemblies": ["kubejs:storage_cell_backplane"],
                "target": "ae2:drive",
                "depends_on": ["processor_manufacturing"],
                "focus_en": "item and type capacity, cell migration, empty-cell reserve, overflow routing and recovery after removing a loaded drive",
                "focus_ru": "ёмкость предметов и типов, перенос ячеек, резерв пустых ячеек, маршрут переполнения и восстановление после снятия заполненного накопителя",
            },
            {
                "slug": "channel_diagnostics",
                "title_en": "Channel diagnostics and network proving",
                "title_ru": "Диагностика каналов и проверка сети",
                "assemblies": ["kubejs:channel_test_fixture"],
                "target": "ae2:fluix_glass_cable",
                "depends_on": ["processor_manufacturing"],
                "focus_en": "channel counting, power loss, cable colour or subnet isolation, visible saturation and restart after disconnecting one branch",
                "focus_ru": "подсчёт каналов, потерю энергии, цветовую или подсетевую изоляцию, видимое насыщение и перезапуск после отключения одной ветви",
            },
        ],
        "integration_item": "kubejs:signal_backplane",
        "optimization_en": "processor throughput, storage type pressure, channel reserve, idle terminals, request latency and recovery after a cable or drive reload",
        "optimization_ru": "скорость процессоров, давление по типам хранения, резерв каналов, простаивающие терминалы, задержку запроса и восстановление после перезагрузки кабеля или накопителя",
    },
    "process_chemistry": {
        "branches": [
            {
                "slug": "pressure_containment",
                "title_en": "Pressure containment line",
                "title_ru": "Линия сдерживания давления",
                "assemblies": ["kubejs:sealed_reaction_vessel"],
                "target": "kubejs:pressure_manifold",
                "focus_en": "sealed volume, pressure limits, valve direction, safe depressurization and recovery after an interrupted pressure recipe",
                "focus_ru": "герметичный объём, пределы давления, направление клапанов, безопасный сброс и восстановление после прерванного рецепта",
            },
            {
                "slug": "gas_distribution",
                "title_en": "Gas distribution and machine casing",
                "title_ru": "Газораспределение и корпус химической машины",
                "assemblies": ["kubejs:gas_distribution_rack"],
                "target": "mekanism:steel_casing",
                "focus_en": "gas identity, side configuration, tube capacity, cross-contamination prevention and isolation of a leaking or full branch",
                "focus_ru": "идентичность газа, настройку сторон, ёмкость труб, защиту от смешивания и изоляцию протекающей или заполненной ветви",
            },
            {
                "slug": "process_control",
                "title_en": "Chemical process control",
                "title_ru": "Управление химическим процессом",
                "assemblies": ["kubejs:process_control_board"],
                "target": "kubejs:precision_circuit",
                "depends_on": ["pressure_containment", "gas_distribution"],
                "focus_en": "recipe locking, secondary-input ownership, phase-aware routing, clean purge and a visible invalid-state response",
                "focus_ru": "фиксацию рецепта, владение дополнительным входом, маршрутизацию по фазам, чистую продувку и видимую реакцию на неверное состояние",
            },
        ],
        "integration_item": "kubejs:precision_circuit",
        "optimization_en": "pressure reserve, gas transfer rate, purge time, circuit batch cost, idle compression and recovery after a full chemical output",
        "optimization_ru": "резерв давления, скорость газов, время продувки, стоимость партии схем, сжатие в простое и восстановление после заполнения химического выхода",
    },
    "industrial_scale": {
        "branches": [
            {
                "slug": "parallel_control",
                "title_en": "Parallel-machine control",
                "title_ru": "Управление параллельными машинами",
                "assemblies": ["kubejs:parallel_machine_bus"],
                "target": "kubejs:chemical_reactor_core",
                "focus_en": "balanced machine lanes, shared-input arbitration, state-based enable signals and isolation of one failed processing module",
                "focus_ru": "баланс линий машин, арбитраж общего входа, включение по состоянию и изоляцию одного отказавшего модуля",
            },
            {
                "slug": "fluid_safety",
                "title_en": "Industrial fluid safety",
                "title_ru": "Безопасность промышленных жидкостей",
                "assemblies": ["kubejs:fluid_safety_block"],
                "target": "industrialforegoing:machine_frame_advanced",
                "focus_en": "tank reserve, source direction, overflow shutdown, incompatible-fluid quarantine and recovery without voiding a valuable batch",
                "focus_ru": "резерв ёмкостей, направление источника, остановку при переполнении, карантин несовместимой жидкости и восстановление без уничтожения ценной партии",
            },
            {
                "slug": "maintenance_access",
                "title_en": "Maintenance access and service standard",
                "title_ru": "Доступ для обслуживания и сервисный стандарт",
                "assemblies": ["kubejs:maintenance_access_frame"],
                "target": None,
                "focus_en": "clear service space, labelled spares, bounded shutdown, replacement order and resuming only the repaired production module",
                "focus_ru": "свободное сервисное пространство, подписанные запчасти, ограниченную остановку, порядок замены и запуск только отремонтированного модуля",
            },
        ],
        "integration_item": "kubejs:chemical_processor",
        "optimization_en": "single-lane and parallel throughput, shared-buffer occupancy, fluid backpressure, idle factories, maintenance time and restart after chunk reload",
        "optimization_ru": "скорость одной и нескольких линий, заполнение общего буфера, обратное давление жидкости, простаивающие фабрики, время обслуживания и перезапуск после загрузки чанка",
    },
}
