<recipetype:extendedcrafting:table>.addShaped("677e8cef-6a08-4714-9dca-4708c20a9c72", 0, <item:modular_machinery_reborn:controller>.withJsonComponent(<componenttype:modular_machinery_reborn:machine>, "mmr:darkness_forge"), [
	[<item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>], 
	[<item:modular_machinery_reborn:modularium>, <item:cataclysm:the_incinerator>, <item:cataclysm:wrath_of_the_desert>, <item:minformax:ultimate_processing_upgrade>, <item:cataclysm:void_forge>, <item:minformax:ultimate_speed_upgrade>, <item:cataclysm:the_immolator>, <item:cataclysm:ceraunus>, <item:modular_machinery_reborn:modularium>], 
	[<item:modular_machinery_reborn:modularium>, <item:ars_elemental:fire_focus>, <item:projecte:dark_matter_block>, <item:projecte:dark_matter_block>, <item:projecte:dark_matter_block>, <item:projecte:dark_matter_block>, <item:projecte:dark_matter_block>, <item:ars_elemental:water_focus>, <item:modular_machinery_reborn:modularium>], 
	[<item:modular_machinery_reborn:modularium>, <item:ars_elemental:air_focus>, <item:projecte:dark_matter_block>, <item:modern_industrialization:replicator>, <item:modular_machinery_reborn:controller>.withJsonComponent(<componenttype:modular_machinery_reborn:machine>, "mmr:catalyst_forge"), <item:modern_industrialization:replicator>, <item:projecte:dark_matter_block>, <item:ars_elemental:earth_focus>, <item:modular_machinery_reborn:modularium>], 
	[<item:modular_machinery_reborn:modularium>, <item:dysoncubeproject:ray_receiver_controller>, <item:projecte:dark_matter_block>, <item:modular_machinery_reborn:controller>.withJsonComponent(<componenttype:modular_machinery_reborn:machine>, "mmr:industrial_grade_assembler"), <item:ars_additions:void_protection_charm>, <item:modular_machinery_reborn:controller>.withJsonComponent(<componenttype:modular_machinery_reborn:machine>, "mmr:cosmic_reciever"), <item:projecte:dark_matter_block>, <item:dysoncubeproject:ray_receiver_controller>, <item:modular_machinery_reborn:modularium>], 
	[<item:modular_machinery_reborn:modularium>, <item:iceandfire:hydra_heart>, <item:projecte:dark_matter_block>, <item:modern_industrialization:replicator>, <item:pneumaticcraft:programmable_controller>, <item:modern_industrialization:replicator>, <item:projecte:dark_matter_block>, <item:iceandfire:fire_dragon_heart>, <item:modular_machinery_reborn:modularium>], 
	[<item:modular_machinery_reborn:modularium>, <item:iceandfire:ice_dragon_heart>, <item:projecte:dark_matter_block>, <item:projecte:dark_matter_block>, <item:projecte:dark_matter_block>, <item:projecte:dark_matter_block>, <item:projecte:dark_matter_block>, <item:iceandfire:lightning_dragon_heart>, <item:modular_machinery_reborn:modularium>], 
	[<item:modular_machinery_reborn:modularium>, <item:apothic_enchanting:draconic_endshelf>, <item:draconicevolution:reactor_core>, <item:mekanism_extras:cosmic_induction_cell>, <item:dysoncubeproject:ray_receiver_controller>, <item:mekanism_extras:cosmic_induction_provider>, <item:draconicevolution:reactor_core>, <item:apothic_enchanting:draconic_endshelf>, <item:modular_machinery_reborn:modularium>], 
	[<item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>, <item:modular_machinery_reborn:modularium>]
]);