<recipetype:extendedcrafting:table>.addShaped("7ce59297-6a94-4feb-90ad-feeb6aea445a", 0, <item:powah:energy_cell_creative>, [
	[<item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:powah:player_transmitter_nitro>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:player_transmitter_nitro>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:solar_panel_nitro>, <item:powah:nitro_crystal_block>, <item:powah:nitro_crystal_block>, <item:powah:nitro_crystal_block>, <item:powah:solar_panel_nitro>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:avaritia:infinity_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:nitro_crystal_block>, <item:powah:nitro_crystal_block>, <item:avaritia:infinity_ingot>, <item:powah:nitro_crystal_block>, <item:powah:nitro_crystal_block>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:avaritia:infinity_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:nitro_crystal_block>, <item:avaritia:infinity_ingot>, <item:powah:energy_cell_nitro>, <item:avaritia:infinity_ingot>, <item:powah:nitro_crystal_block>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:avaritia:infinity_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:nitro_crystal_block>, <item:powah:nitro_crystal_block>, <item:avaritia:infinity_ingot>, <item:powah:nitro_crystal_block>, <item:powah:nitro_crystal_block>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:avaritia:infinity_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:solar_panel_nitro>, <item:powah:nitro_crystal_block>, <item:powah:nitro_crystal_block>, <item:powah:nitro_crystal_block>, <item:powah:solar_panel_nitro>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:avaritia:infinity_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:powah:player_transmitter_nitro>, <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:battery_nitro>.withJsonComponent(<componenttype:powah:energy_stored>, 2000000000), <item:powah:player_transmitter_nitro>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>]
]);