<recipetype:extendedcrafting:table>.addShaped("a6c903c2-e94f-4344-b0e2-c7a584efadc7", 0, <item:fragmentumneoforge:rocket>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:stellaris:desh_ingot>, <item:stellaris:desh_ingot>, <item:stellaris:desh_ingot>, <item:stellaris:desh_ingot>, <item:stellaris:desh_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:stellaris:desh_ingot>, <item:stellaris:ice_shard>, <item:stellaris:ice_shard>, <item:stellaris:plutonium_ingot>, <item:stellaris:ice_shard>, <item:stellaris:ice_shard>, <item:stellaris:desh_ingot>, <item:minecraft:air>], 
	[<item:stellaris:desh_ingot>, <item:stellaris:ice_shard>, <item:stellaris:ice_shard>, <item:stellaris:plutonium_ingot>, <item:forbidden_arcanus:eternal_stella>, <item:stellaris:plutonium_ingot>, <item:stellaris:ice_shard>, <item:stellaris:ice_shard>, <item:stellaris:desh_ingot>], 
	[<item:stellaris:desh_ingot>, <item:stellaris:ice_shard>, <item:stellaris:ice_shard>, <item:stellaris:plutonium_ingot>, <item:industrialforegoing:machine_frame_supreme>, <item:stellaris:plutonium_ingot>, <item:stellaris:ice_shard>, <item:stellaris:ice_shard>, <item:stellaris:desh_ingot>], 
	[<item:stellaris:desh_ingot>, <item:stellaris:ice_shard>, <item:stellaris:ice_shard>, <item:stellaris:plutonium_ingot>, <item:stellaris:rocket>, <item:stellaris:plutonium_ingot>, <item:stellaris:ice_shard>, <item:stellaris:ice_shard>, <item:stellaris:desh_ingot>], 
	[<item:stellaris:desh_ingot>, <item:stellaris:ice_shard>, <item:stellaris:ice_shard>, <item:stellaris:plutonium_ingot>, <item:cognition:bibliophage>, <item:stellaris:plutonium_ingot>, <item:stellaris:ice_shard>, <item:stellaris:ice_shard>, <item:stellaris:desh_ingot>], 
	[<item:stellaris:desh_ingot>, <item:stellaris:ice_shard>, <item:stellaris:plutonium_ingot>, <item:stellaris:hydrogen_motor>, <item:stellaris:plutonium_ingot>, <item:stellaris:radioactive_motor>, <item:stellaris:plutonium_ingot>, <item:stellaris:ice_shard>, <item:stellaris:desh_ingot>], 
	[<item:minecraft:air>, <item:stellaris:desh_ingot>, <item:stellaris:plutonium_ingot>, <item:stellaris:solerium>, <item:stellaris:solerium>, <item:stellaris:solerium>, <item:stellaris:plutonium_ingot>, <item:stellaris:desh_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:stellaris:desh_ingot>, <item:stellaris:desh_ingot>, <item:stellaris:desh_ingot>, <item:stellaris:desh_ingot>, <item:stellaris:desh_ingot>, <item:minecraft:air>, <item:minecraft:air>]
]);