<recipetype:extendedcrafting:table>.addShaped("d088f581-fae7-43d6-b7be-af37aa0a8ae0", 0, <item:kubejs:sus_shell>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:irons_spellbooks:mithril_weave>, <item:irons_spellbooks:mithril_weave>, <item:irons_spellbooks:mithril_weave>, <item:irons_spellbooks:mithril_weave>, <item:irons_spellbooks:mithril_weave>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:minecraft:air>], 
	[<item:actuallyadditions:empowered_enori_crystal_block>, <item:irons_spellbooks:mithril_weave>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:irons_spellbooks:mithril_weave>, <item:actuallyadditions:empowered_enori_crystal_block>], 
	[<item:actuallyadditions:empowered_enori_crystal_block>, <item:irons_spellbooks:mithril_weave>, <item:projectexpansion:white_matter>, <item:occultism:iesnium_ingot>, <item:occultism:iesnium_ingot>, <item:occultism:iesnium_ingot>, <item:projectexpansion:white_matter>, <item:irons_spellbooks:mithril_weave>, <item:actuallyadditions:empowered_enori_crystal_block>], 
	[<item:actuallyadditions:empowered_enori_crystal_block>, <item:irons_spellbooks:mithril_weave>, <item:projectexpansion:white_matter>, <item:occultism:iesnium_ingot>, <item:woot_revived:prism>, <item:occultism:iesnium_ingot>, <item:projectexpansion:white_matter>, <item:irons_spellbooks:mithril_weave>, <item:actuallyadditions:empowered_enori_crystal_block>], 
	[<item:actuallyadditions:empowered_enori_crystal_block>, <item:irons_spellbooks:mithril_weave>, <item:projectexpansion:white_matter>, <item:occultism:iesnium_ingot>, <item:occultism:iesnium_ingot>, <item:occultism:iesnium_ingot>, <item:projectexpansion:white_matter>, <item:irons_spellbooks:mithril_weave>, <item:actuallyadditions:empowered_enori_crystal_block>], 
	[<item:actuallyadditions:empowered_enori_crystal_block>, <item:irons_spellbooks:mithril_weave>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:irons_spellbooks:mithril_weave>, <item:actuallyadditions:empowered_enori_crystal_block>], 
	[<item:minecraft:air>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:irons_spellbooks:mithril_weave>, <item:irons_spellbooks:mithril_weave>, <item:irons_spellbooks:mithril_weave>, <item:irons_spellbooks:mithril_weave>, <item:irons_spellbooks:mithril_weave>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:actuallyadditions:empowered_enori_crystal_block>, <item:minecraft:air>, <item:minecraft:air>]
]);