<recipetype:extendedcrafting:table>.addShaped("7935c3dd-b55b-4542-a788-2c1071ff37bd", 0, <item:mysticalagradditions:creative_essence>, [
	[<item:mysticalagradditions:insanium_block>, <item:minecraft:air>, <item:mysticalagradditions:insanium_block>, <item:minecraft:air>, <item:mysticalagradditions:insanium_block>, <item:minecraft:air>, <item:mysticalagradditions:insanium_block>, <item:minecraft:air>, <item:mysticalagradditions:insanium_block>], 
	[<item:mysticalagradditions:insanium_block>, <item:minecraft:air>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:minecraft:air>, <item:mysticalagradditions:insanium_block>], 
	[<item:minecraft:air>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_block>, <item:minecraft:air>], 
	[<item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_block>], 
	[<item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_block>], 
	[<item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_block>], 
	[<item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_ingot_block>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_block>], 
	[<item:minecraft:air>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_gemstone_block>, <item:mysticalagradditions:insanium_block>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:mysticalagradditions:insanium_block>, <item:minecraft:air>, <item:minecraft:air>]
]);