<recipetype:extendedcrafting:table>.addShaped("10cb48a3-8ff1-40fe-aeca-7c21423abe1a", 0, <item:fragmentumneoforge:flos>, [
	[<item:mysticalagriculture:awakened_supremium_block>, <item:minecraft:air>, <item:minecraft:air>, <item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:awakened_supremium_block>, <item:minecraft:air>, <item:minecraft:air>, <item:mysticalagriculture:awakened_supremium_block>], 
	[<item:minecraft:air>, <item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:nether_star_seeds>, <item:mysticalagradditions:creative_essence>, <item:mysticalagriculture:uraninite_seeds>, <item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:awakened_supremium_block>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:nitro_crystal_seeds>, <item:mysticalagriculture:supremium_block>, <item:mysticalagriculture:supremium_block>, <item:mysticalagriculture:supremium_block>, <item:mysticalagriculture:dragon_egg_seeds>, <item:mysticalagriculture:awakened_supremium_block>, <item:minecraft:air>], 
	[<item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:cognizant_dust>, <item:mysticalagradditions:creative_essence>, <item:mysticalagriculture:supremium_block>, <item:mysticalagradditions:creative_essence>, <item:mysticalagriculture:supremium_block>, <item:mysticalagradditions:creative_essence>, <item:mysticalagriculture:cognizant_dust>, <item:mysticalagriculture:awakened_supremium_block>], 
	[<item:minecraft:air>, <item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:neutronium_seeds>, <item:mysticalagriculture:supremium_block>, <item:mysticalagriculture:supremium_block>, <item:mysticalagriculture:supremium_block>, <item:mysticalagriculture:awakened_draconium_seeds>, <item:mysticalagriculture:awakened_supremium_block>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:mysticalagriculture:prudentium_block>, <item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:awakened_supremium_block>, <item:projectexpansion:final_power_flower>, <item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:awakened_supremium_block>, <item:mysticalagriculture:prudentium_block>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:mysticalagriculture:prudentium_block>, <item:mysticalagriculture:prudentium_block>, <item:mysticalagriculture:prudentium_block>, <item:mysticalagriculture:prudentium_block>, <item:mysticalagriculture:prudentium_block>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:mysticalagriculture:prudentium_block>, <item:minecraft:air>, <item:minecraft:air>, <item:mysticalagriculture:prudentium_block>, <item:minecraft:air>, <item:minecraft:air>, <item:mysticalagriculture:prudentium_block>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:mysticalagriculture:prudentium_block>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);