recipes.remove(<item:projecte:philosophers_stone>);<recipetype:extendedcrafting:table>.addShaped("c3ce49a5-8f91-4fff-a961-f0764fd56b2a", 0, <item:projecte:philosophers_stone>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:mysticalagriculture:supremium_ingot>, <item:allthecompressed:ruby_block_3x>, <item:allthecompressed:ruby_block_3x>, <item:allthecompressed:ruby_block_3x>, <item:allthecompressed:ruby_block_3x>, <item:allthecompressed:ruby_block_3x>, <item:mysticalagriculture:supremium_ingot>, <item:minecraft:air>], 
	[<item:mysticalagriculture:supremium_ingot>, <item:allthecompressed:ruby_block_3x>, <item:advanced_ae:quantum_processor>, <item:advanced_ae:quantum_processor>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:irons_spellbooks:fire_upgrade_orb>, <item:allthecompressed:ruby_block_3x>, <item:mysticalagriculture:supremium_ingot>], 
	[<item:mysticalagriculture:supremium_ingot>, <item:allthecompressed:ruby_block_3x>, <item:advanced_ae:quantum_processor>, <item:advanced_ae:quantum_processor>, <item:mekanism_extras:alloy_thermonuclear>, <item:forbidden_arcanus:mundabitur_dust>, <item:extendedcrafting:crystaltine_ingot>, <item:allthecompressed:ruby_block_3x>, <item:mysticalagriculture:supremium_ingot>], 
	[<item:mysticalagriculture:supremium_ingot>, <item:allthecompressed:ruby_block_3x>, <item:extendedcrafting:crystaltine_ingot>, <item:advancednetherite:netherite_diamond_ingot>, <item:extendedcrafting:ultimate_catalyst>, <item:advancednetherite:netherite_diamond_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:allthecompressed:ruby_block_3x>, <item:mysticalagriculture:supremium_ingot>], 
	[<item:mysticalagriculture:supremium_ingot>, <item:allthecompressed:ruby_block_3x>, <item:extendedcrafting:crystaltine_ingot>, <item:industrialforegoing:machine_frame_supreme>, <item:mekanism_extras:alloy_thermonuclear>, <item:industrialforegoing:machine_frame_supreme>, <item:extendedcrafting:crystaltine_ingot>, <item:allthecompressed:ruby_block_3x>, <item:mysticalagriculture:supremium_ingot>], 
	[<item:mysticalagriculture:supremium_ingot>, <item:allthecompressed:ruby_block_3x>, <item:irons_spellbooks:fire_upgrade_orb>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:irons_spellbooks:fire_upgrade_orb>, <item:allthecompressed:ruby_block_3x>, <item:mysticalagriculture:supremium_ingot>], 
	[<item:minecraft:air>, <item:mysticalagriculture:supremium_ingot>, <item:allthecompressed:ruby_block_3x>, <item:allthecompressed:ruby_block_3x>, <item:allthecompressed:ruby_block_3x>, <item:allthecompressed:ruby_block_3x>, <item:allthecompressed:ruby_block_3x>, <item:mysticalagriculture:supremium_ingot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:minecraft:air>, <item:minecraft:air>]
]);