recipes.remove(<item:projecte:transmutation_tablet>);<recipetype:extendedcrafting:table>.addShaped("70b6edaa-e2dc-4569-804a-d1f7a0c2b6b8", 0, <item:projecte:transmutation_tablet>, [
	[<item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>], 
	[<item:projectexpansion:fading_matter_block>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:purple_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:fading_matter_block>], 
	[<item:projectexpansion:fading_matter_block>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:gateways:gate_pearl>.withJsonComponent(<componenttype:gateways:gateway>, "apotheosis:tiered/pinnacle"), <item:projectexpansion:purple_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:fading_matter_block>], 
	[<item:projectexpansion:fading_matter_block>, <item:projectexpansion:white_matter>, <item:projectexpansion:purple_matter>, <item:projectexpansion:purple_matter>, <item:projectexpansion:pink_matter>, <item:projectexpansion:purple_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:fading_matter_block>], 
	[<item:projectexpansion:fading_matter_block>, <item:projectexpansion:purple_matter>, <item:occultism:trinity_gem>, <item:projectexpansion:pink_matter>, <item:projecte:transmutation_table>, <item:projectexpansion:pink_matter>, <item:irons_spellbooks:dragonskin_spell_book>.withJsonComponent(<componenttype:irons_spellbooks:spell_container>, {mustEquip: true, maxSpells: 12, data: [], spellWheel: true}), <item:projectexpansion:purple_matter>, <item:projectexpansion:fading_matter_block>], 
	[<item:projectexpansion:fading_matter_block>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:purple_matter>, <item:projectexpansion:pink_matter>, <item:projectexpansion:purple_matter>, <item:projectexpansion:purple_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:fading_matter_block>], 
	[<item:projectexpansion:fading_matter_block>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:purple_matter>, <item:naturesaura:death_ring>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:fading_matter_block>], 
	[<item:projectexpansion:fading_matter_block>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:purple_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:white_matter>, <item:projectexpansion:fading_matter_block>], 
	[<item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>, <item:projectexpansion:fading_matter_block>]
]);