recipes.remove(<item:projecte:transmutation_table>);<recipetype:extendedcrafting:table>.addShaped("93607fe4-8a60-4f49-a434-91a4ea1fb2ff", 0, <item:projecte:transmutation_table>, [
	[<item:avaritia:neutron>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:avaritia:neutron>], 
	[<item:allthecompressed:sky_stone_block_5x>, <item:draconicevolution:awakened_draconium_block>, <item:modern_industrialization:quantum_circuit_board>, <item:modern_industrialization:quantum_circuit_board>, <item:projectexpansion:purple_matter>, <item:modern_industrialization:quantum_circuit_board>, <item:modern_industrialization:quantum_circuit_board>, <item:draconicevolution:awakened_draconium_block>, <item:allthecompressed:sky_stone_block_5x>], 
	[<item:allthecompressed:sky_stone_block_5x>, <item:modern_industrialization:quantum_circuit_board>, <item:ae2additions:super_cell_component_65m>, <item:cataclysm:wrath_of_the_desert>, <item:extendedcrafting:ultimate_singularity>, <item:projectexpansion:purple_matter>, <item:occultism:celestial_chalice>, <item:modern_industrialization:quantum_circuit_board>, <item:allthecompressed:sky_stone_block_5x>], 
	[<item:allthecompressed:sky_stone_block_5x>, <item:modern_industrialization:quantum_circuit_board>, <item:projectexpansion:purple_matter>, <item:projectexpansion:purple_matter>, <item:projectexpansion:pink_matter>, <item:projectexpansion:purple_matter>, <item:cataclysm:ceraunus>, <item:modern_industrialization:quantum_circuit_board>, <item:allthecompressed:sky_stone_block_5x>], 
	[<item:allthecompressed:sky_stone_block_5x>, <item:projectexpansion:purple_matter>, <item:extendedcrafting:ultimate_singularity>, <item:projectexpansion:pink_matter>, <item:projecte:philosophers_stone>, <item:projectexpansion:pink_matter>, <item:extendedcrafting:ultimate_singularity>, <item:projectexpansion:purple_matter>, <item:allthecompressed:sky_stone_block_5x>], 
	[<item:allthecompressed:sky_stone_block_5x>, <item:modern_industrialization:quantum_circuit_board>, <item:cataclysm:meat_shredder>, <item:projectexpansion:purple_matter>, <item:projectexpansion:pink_matter>, <item:projectexpansion:purple_matter>, <item:projectexpansion:purple_matter>, <item:modern_industrialization:quantum_circuit_board>, <item:allthecompressed:sky_stone_block_5x>], 
	[<item:allthecompressed:sky_stone_block_5x>, <item:modern_industrialization:quantum_circuit_board>, <item:occultism:eldritch_chalice>, <item:projectexpansion:purple_matter>, <item:extendedcrafting:ultimate_singularity>, <item:cataclysm:the_incinerator>, <item:pneumaticcraft:programmable_controller>, <item:modern_industrialization:quantum_circuit_board>, <item:allthecompressed:sky_stone_block_5x>], 
	[<item:allthecompressed:sky_stone_block_5x>, <item:draconicevolution:awakened_draconium_block>, <item:modern_industrialization:quantum_circuit_board>, <item:modern_industrialization:quantum_circuit_board>, <item:projectexpansion:purple_matter>, <item:modern_industrialization:quantum_circuit_board>, <item:modern_industrialization:quantum_circuit_board>, <item:draconicevolution:awakened_draconium_block>, <item:allthecompressed:sky_stone_block_5x>], 
	[<item:avaritia:neutron>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:allthecompressed:sky_stone_block_5x>, <item:avaritia:neutron>]
]);