recipes.remove(<item:extendedcrafting:the_ultimate_ingot>);<recipetype:extendedcrafting:table>.addShaped("bd684a05-928c-4630-ad81-631cd03f2468", 0, <item:extendedcrafting:the_ultimate_ingot>, [
	[<item:enderio:energetic_alloy_ingot>, <item:enderio:vibrant_alloy_ingot>, <item:enderio:redstone_alloy_ingot>, <item:enderio:conductive_alloy_ingot>, <item:enderio:pulsating_alloy_ingot>, <item:enderio:dark_steel_ingot>, <item:enderio:soularium_ingot>, <item:enderio:end_steel_ingot>, <item:industrialforegoing:pink_slime_ingot>], 
	[<item:occultism:iesnium_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:enhanced_redstone_ingot>, <item:extendedcrafting:ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:mysticalagriculture:prosperity_ingot>, <item:mysticalagriculture:inferium_ingot>], 
	[<item:mysticalagriculture:prudentium_ingot>, <item:mysticalagriculture:tertium_ingot>, <item:mysticalagriculture:imperium_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:awakened_supremium_ingot>, <item:mysticalagradditions:insanium_ingot>, <item:bigreactors:blutonium_ingot>, <item:bigreactors:cyanite_ingot>, <item:draconicevolution:awakened_draconium_ingot>], 
	[<item:draconicevolution:draconium_ingot>, <item:mekanism:ingot_refined_obsidian>, <item:mekanism:ingot_refined_glowstone>, <item:mekanism_extras:ingot_naquadah>, <item:pneumaticcraft:ingot_iron_compressed>, <item:immersiveengineering:ingot_hop_graphite>, <item:aquaculture:neptunium_ingot>, <item:stellaris:desh_ingot>, <item:bigreactors:magentite_ingot>], 
	[<item:bigreactors:ludicrite_ingot>, <item:bigreactors:ridiculite_ingot>, <item:bigreactors:inanite_ingot>, <item:bigreactors:insanite_ingot>, <item:mekanism_extras:alloy_spectrum>, <item:avaritia:crystal_matrix_ingot>, <item:modern_industrialization:plutonium_ingot>, <item:extendedae:entro_ingot>, <item:megacells:sky_steel_ingot>], 
	[<item:justdirethings:ferricore_ingot>, <item:justdirethings:blazegold_ingot>, <item:justdirethings:eclipsealloy_ingot>, <item:stellaris:heavy_metal_ingot>, <item:megacells:sky_bronze_ingot>, <item:megacells:sky_osmium_ingot>, <item:cognition:cognitive_alloy>, <item:advanced_ae:quantum_alloy>, <item:allthemodium:allthemodium_ingot>], 
	[<item:allthemodium:vibranium_ingot>, <item:allthemodium:unobtainium_ingot>, <item:forbidden_arcanus:deorum_ingot>, <item:modern_industrialization:uranium_238_ingot>, <item:modern_industrialization:uranium_235_ingot>, <item:alltheores:uranium_ingot>, <item:modern_industrialization:tungsten_ingot>, <item:modern_industrialization:titanium_ingot>, <item:modern_industrialization:superconductor_ingot>], 
	[<item:modern_industrialization:stainless_steel_ingot>, <item:modern_industrialization:annealed_copper_ingot>, <item:modern_industrialization:antimony_ingot>, <item:modern_industrialization:battery_alloy_ingot>, <item:modern_industrialization:beryllium_ingot>, <item:modern_industrialization:blastproof_alloy_ingot>, <item:modern_industrialization:cadmium_ingot>, <item:modern_industrialization:chromium_ingot>, <item:modern_industrialization:cupronickel_ingot>], 
	[<item:modern_industrialization:he_mox_ingot>, <item:modern_industrialization:he_uranium_ingot>, <item:modern_industrialization:kanthal_ingot>, <item:minformax:ultimate_ingot>, <item:minformax:void_ingot>, <item:woot_revived:stygian_ingot>, <item:modern_industrialization:silicon_ingot>, <item:forbidden_arcanus:obsidiansteel_ingot>, <item:mysticalagriculture:soulium_ingot>]
]);