<recipetype:extendedcrafting:table>.addShaped("062745a5-ad89-4705-a7f7-58fd51547f80", 0, <item:mekanism_extras:upgrade_creative>, [
	[<item:mekanism:steel_casing>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:steel_casing>], 
	[<item:mekanism:steel_casing>, <item:mysticalagradditions:creative_essence>, <item:mekanism:alloy_atomic>, <item:mekanism:alloy_atomic>, <item:mekanism:alloy_atomic>, <item:mekanism:alloy_atomic>, <item:mekanism:alloy_atomic>, <item:mekanism:upgrade_speed>, <item:mekanism:steel_casing>], 
	[<item:mekanism:steel_casing>, <item:mekanism:alloy_reinforced>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_energy>, <item:mekanism:alloy_reinforced>, <item:mekanism:steel_casing>], 
	[<item:mekanism:steel_casing>, <item:mekanism:alloy_atomic>, <item:mekanism:upgrade_energy>, <item:mekanism:pellet_antimatter>, <item:mekanism:alloy_infused>, <item:mekanism:pellet_antimatter>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_speed>, <item:mekanism:steel_casing>], 
	[<item:mekanism:steel_casing>, <item:mekanism:alloy_atomic>, <item:mekanism:upgrade_energy>, <item:mekanism:alloy_infused>, <item:mekanism_extras:infinite_control_circuit>, <item:mekanism:alloy_infused>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_speed>, <item:mekanism:steel_casing>], 
	[<item:mekanism:steel_casing>, <item:mekanism:alloy_atomic>, <item:mekanism:upgrade_energy>, <item:mekanism:pellet_antimatter>, <item:mekanism:alloy_infused>, <item:mekanism:pellet_antimatter>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_speed>, <item:mekanism:steel_casing>], 
	[<item:mekanism:steel_casing>, <item:mekanism:alloy_reinforced>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_energy>, <item:mekanism:upgrade_energy>, <item:mekanism:alloy_reinforced>, <item:mekanism:steel_casing>], 
	[<item:mekanism:steel_casing>, <item:mysticalagradditions:creative_essence>, <item:mekanism:alloy_atomic>, <item:mekanism:alloy_atomic>, <item:mekanism:alloy_atomic>, <item:mekanism:alloy_atomic>, <item:mekanism:alloy_atomic>, <item:mekanism:upgrade_speed>, <item:mekanism:steel_casing>], 
	[<item:mekanism:steel_casing>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:structural_glass>, <item:mekanism:steel_casing>]
]);