<recipetype:extendedcrafting:table>.addShaped("6ce0c2bb-ddc1-4a80-83a8-c63492a3d8f3", 0, <item:kubejs:multi_quantum_processor>, [
	[<item:immersiveengineering:ingot_hop_graphite>, <item:allthemodium:vibranium_ingot>, <item:immersiveengineering:ingot_hop_graphite>, <item:allthemodium:vibranium_ingot>, <item:immersiveengineering:ingot_hop_graphite>, <item:allthemodium:vibranium_ingot>, <item:immersiveengineering:ingot_hop_graphite>, <item:allthemodium:vibranium_ingot>, <item:immersiveengineering:ingot_hop_graphite>], 
	[<item:allthemodium:vibranium_ingot>, <item:modern_industrialization:quantum_circuit_board>, <item:modern_industrialization:quantum_circuit_board>, <item:modern_industrialization:quantum_circuit_board>, <item:modern_industrialization:quantum_circuit_board>, <item:modern_industrialization:quantum_circuit_board>, <item:modern_industrialization:quantum_circuit_board>, <item:modern_industrialization:quantum_circuit_board>, <item:allthemodium:vibranium_ingot>], 
	[<item:immersiveengineering:ingot_hop_graphite>, <item:modern_industrialization:quantum_circuit_board>, <item:mekanism:pellet_antimatter>, <item:modern_industrialization:platinum_fine_wire>, <item:modern_industrialization:platinum_fine_wire>, <item:modern_industrialization:platinum_fine_wire>, <item:mekanism:pellet_antimatter>, <item:modern_industrialization:quantum_circuit_board>, <item:immersiveengineering:ingot_hop_graphite>], 
	[<item:allthemodium:vibranium_ingot>, <item:modern_industrialization:platinum_fine_wire>, <item:modern_industrialization:platinum_fine_wire>, <item:modern_industrialization:platinum_fine_wire>, <item:advanced_ae:quantum_processor>, <item:modern_industrialization:platinum_fine_wire>, <item:modern_industrialization:platinum_fine_wire>, <item:modern_industrialization:platinum_fine_wire>, <item:allthemodium:vibranium_ingot>], 
	[<item:immersiveengineering:ingot_hop_graphite>, <item:modern_industrialization:platinum_fine_wire>, <item:modern_industrialization:resistor>, <item:tfmg:transistor_item>, <item:mekanism_extras:infinite_control_circuit>, <item:tfmg:transistor_item>, <item:modern_industrialization:resistor>, <item:modern_industrialization:platinum_fine_wire>, <item:immersiveengineering:ingot_hop_graphite>], 
	[<item:allthemodium:vibranium_ingot>, <item:modern_industrialization:platinum_fine_wire>, <item:enderio:guardian_diode>, <item:modern_industrialization:transistor>, <item:draconicevolution:chaotic_core>, <item:modern_industrialization:transistor>, <item:enderio:guardian_diode>, <item:modern_industrialization:platinum_fine_wire>, <item:allthemodium:vibranium_ingot>], 
	[<item:immersiveengineering:ingot_hop_graphite>, <item:pneumaticcraft:printed_circuit_board>, <item:pneumaticcraft:printed_circuit_board>, <item:pneumaticcraft:transistor>, <item:pneumaticcraft:printed_circuit_board>, <item:pneumaticcraft:transistor>, <item:pneumaticcraft:printed_circuit_board>, <item:pneumaticcraft:printed_circuit_board>, <item:immersiveengineering:ingot_hop_graphite>], 
	[<item:allthemodium:vibranium_ingot>, <item:immersiveengineering:component_electronic_adv>, <item:megacells:cell_component_256m>, <item:pneumaticcraft:printed_circuit_board>, <item:mekanism:pellet_antimatter>, <item:pneumaticcraft:printed_circuit_board>, <item:megacells:cell_component_256m>, <item:immersiveengineering:component_electronic_adv>, <item:allthemodium:vibranium_ingot>], 
	[<item:immersiveengineering:ingot_hop_graphite>, <item:allthemodium:vibranium_ingot>, <item:immersiveengineering:ingot_hop_graphite>, <item:allthemodium:vibranium_ingot>, <item:immersiveengineering:ingot_hop_graphite>, <item:allthemodium:vibranium_ingot>, <item:immersiveengineering:ingot_hop_graphite>, <item:allthemodium:vibranium_ingot>, <item:immersiveengineering:ingot_hop_graphite>]
]);