<recipetype:extendedcrafting:table>.addShaped("70dfa699-f120-4404-8fae-455f438d022e", 0, <item:create:creative_crate>, [
	[<item:projectexpansion:purple_matter_block>, <item:projectexpansion:purple_matter_block>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_catalyst>, <item:projectexpansion:purple_matter_block>, <item:projectexpansion:purple_matter_block>], 
	[<item:projectexpansion:purple_matter_block>, <item:avaritia:infinity_catalyst>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:infinity_catalyst>, <item:projectexpansion:purple_matter_block>], 
	[<item:avaritia:infinity_catalyst>, <item:avaritia:neutron>, <item:tfmg:steel_mechanism>, <item:create:precision_mechanism>, <item:create:precision_mechanism>, <item:create:precision_mechanism>, <item:tfmg:steel_mechanism>, <item:avaritia:neutron>, <item:avaritia:infinity_catalyst>], 
	[<item:avaritia:infinity_ingot>, <item:avaritia:neutron>, <item:create:precision_mechanism>, <item:tfmg:steel_mechanism>, <item:create_enchantment_industry:super_experience_block>, <item:tfmg:steel_mechanism>, <item:create:precision_mechanism>, <item:avaritia:neutron>, <item:avaritia:infinity_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:avaritia:neutron>, <item:create:precision_mechanism>, <item:create_enchantment_industry:super_experience_block>, <item:avaritia:infinity_totem>, <item:create_enchantment_industry:super_experience_block>, <item:create:precision_mechanism>, <item:avaritia:neutron>, <item:avaritia:infinity_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:avaritia:neutron>, <item:create:precision_mechanism>, <item:tfmg:steel_mechanism>, <item:create_enchantment_industry:super_experience_block>, <item:tfmg:steel_mechanism>, <item:create:precision_mechanism>, <item:avaritia:neutron>, <item:avaritia:infinity_ingot>], 
	[<item:avaritia:infinity_catalyst>, <item:avaritia:neutron>, <item:tfmg:steel_mechanism>, <item:create:precision_mechanism>, <item:create:precision_mechanism>, <item:create:precision_mechanism>, <item:tfmg:steel_mechanism>, <item:avaritia:neutron>, <item:avaritia:infinity_catalyst>], 
	[<item:projectexpansion:purple_matter_block>, <item:avaritia:infinity_catalyst>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:infinity_catalyst>, <item:projectexpansion:purple_matter_block>], 
	[<item:projectexpansion:purple_matter_block>, <item:projectexpansion:purple_matter_block>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_catalyst>, <item:projectexpansion:purple_matter_block>, <item:projectexpansion:purple_matter_block>]
]);