<recipetype:extendedcrafting:table>.addShaped("70dfa699-f120-4404-8fae-455f438d034e", 0, <item:createaddition:creative_energy>, [
	[<item:projectexpansion:purple_matter_block>, <item:projectexpansion:purple_matter_block>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_catalyst>, <item:projectexpansion:purple_matter_block>, <item:projectexpansion:purple_matter_block>], 
	[<item:projectexpansion:purple_matter_block>, <item:avaritia:infinity_catalyst>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:infinity_catalyst>, <item:projectexpansion:purple_matter_block>], 
	[<item:avaritia:infinity_catalyst>, <item:avaritia:neutron>, <item:tfmg:steel_mechanism>, <item:create:precision_mechanism>, <item:create:precision_mechanism>, <item:create:precision_mechanism>, <item:tfmg:steel_mechanism>, <item:avaritia:neutron>, <item:avaritia:infinity_catalyst>], 
	[<item:avaritia:infinity_ingot>, <item:avaritia:neutron>, <item:create:precision_mechanism>, <item:tfmg:steel_mechanism>, <item:tfmg:generator>, <item:tfmg:steel_mechanism>, <item:create:precision_mechanism>, <item:avaritia:neutron>, <item:avaritia:infinity_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:avaritia:neutron>, <item:create:precision_mechanism>, <item:tfmg:generator>, <item:createaddition:alternator>, <item:tfmg:generator>, <item:create:precision_mechanism>, <item:avaritia:neutron>, <item:avaritia:infinity_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:avaritia:neutron>, <item:create:precision_mechanism>, <item:tfmg:steel_mechanism>, <item:tfmg:generator>, <item:tfmg:steel_mechanism>, <item:create:precision_mechanism>, <item:avaritia:neutron>, <item:avaritia:infinity_ingot>], 
	[<item:avaritia:infinity_catalyst>, <item:avaritia:neutron>, <item:tfmg:steel_mechanism>, <item:create:precision_mechanism>, <item:create:precision_mechanism>, <item:create:precision_mechanism>, <item:tfmg:steel_mechanism>, <item:avaritia:neutron>, <item:avaritia:infinity_catalyst>], 
	[<item:projectexpansion:purple_matter_block>, <item:avaritia:infinity_catalyst>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:neutron>, <item:avaritia:infinity_catalyst>, <item:projectexpansion:purple_matter_block>], 
	[<item:projectexpansion:purple_matter_block>, <item:projectexpansion:purple_matter_block>, <item:avaritia:infinity_catalyst>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_catalyst>, <item:projectexpansion:purple_matter_block>, <item:projectexpansion:purple_matter_block>]
]);