<recipetype:extendedcrafting:table>.addShaped("6fb91241-3478-49d7-bbcd-96a14bdb21b4", 0, <item:kubejs:information_disk>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:advanced_ae:quantum_alloy_plate>, <item:advanced_ae:quantum_alloy_plate>, <item:advanced_ae:quantum_alloy_plate>, <item:advanced_ae:quantum_alloy_plate>, <item:advanced_ae:quantum_alloy_plate>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:advanced_ae:quantum_alloy_plate>, <item:ae2:spatial_anchor>, <item:allthecompressed:fluix_block_5x>, <item:megacells:1m_crafting_storage>, <item:allthecompressed:fluix_block_5x>, <item:ae2:not_so_mysterious_cube>, <item:advanced_ae:quantum_alloy_plate>, <item:minecraft:air>], 
	[<item:advanced_ae:quantum_alloy_plate>, <item:allthecompressed:fluix_block_5x>, <item:allthecompressed:sky_osmium_block_6x>, <item:allthecompressed:sky_steel_block_6x>, <item:allthecompressed:entro_block_6x>, <item:allthecompressed:sky_bronze_block_6x>, <item:megacells:mega_energy_cell>.withJsonComponent(<componenttype:ae2:stored_energy>, 1.28E7), <item:allthecompressed:fluix_block_5x>, <item:advanced_ae:quantum_alloy_plate>], 
	[<item:advanced_ae:quantum_alloy_plate>, <item:ae2:logic_processor>, <item:ae2:calculation_processor>, <item:ae2:engineering_processor>, <item:appflux:energy_processor>, <item:extendedae:concurrent_processor>, <item:advanced_ae:quantum_processor>, <item:megacells:accumulation_processor>, <item:advanced_ae:quantum_alloy_plate>], 
	[<item:advanced_ae:quantum_alloy_plate>, <item:allthecompressed:fluix_block_5x>, <item:allthecompressed:fluix_block_5x>, <item:allthecompressed:fluix_block_5x>, <item:advanced_ae:data_entangler>, <item:allthecompressed:fluix_block_5x>, <item:allthecompressed:fluix_block_5x>, <item:allthecompressed:fluix_block_5x>, <item:advanced_ae:quantum_alloy_plate>], 
	[<item:advanced_ae:quantum_alloy_plate>, <item:allthecompressed:certus_quartz_block_5x>, <item:allthecompressed:fluix_block_5x>, <item:allthecompressed:fluix_block_5x>, <item:avaritia:star_fuel_block>, <item:allthecompressed:fluix_block_5x>, <item:allthecompressed:fluix_block_5x>, <item:allthecompressed:certus_quartz_block_5x>, <item:advanced_ae:quantum_alloy_plate>], 
	[<item:advanced_ae:quantum_alloy_plate>, <item:appflux:fe_256m_portable_cell>.withJsonComponent(<componenttype:ae2:stored_energy>, 160000.0), <item:allthecompressed:certus_quartz_block_5x>, <item:allthecompressed:certus_quartz_block_5x>, <item:allthecompressed:certus_quartz_block_5x>, <item:allthecompressed:certus_quartz_block_5x>, <item:allthecompressed:certus_quartz_block_5x>, <item:megacells:portable_source_cell_256m>.withJsonComponent(<componenttype:ae2:stored_energy>, 20000.0), <item:advanced_ae:quantum_alloy_plate>], 
	[<item:minecraft:air>, <item:advanced_ae:quantum_alloy_plate>, <item:enderdrives:ender_storage_component_256k>, <item:megacells:cell_component_256m>, <item:ae2additions:super_cell_component_65m>, <item:ae2additions:cell_component_65536>, <item:appflux:core_256m>, <item:advanced_ae:quantum_alloy_plate>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:advanced_ae:quantum_alloy_plate>, <item:advanced_ae:quantum_alloy_plate>, <item:advanced_ae:quantum_alloy_plate>, <item:advanced_ae:quantum_alloy_plate>, <item:advanced_ae:quantum_alloy_plate>, <item:minecraft:air>, <item:minecraft:air>]
]);