<recipetype:extendedcrafting:table>.addShaped("fb829d95-448d-4954-8c69-fac450d3b714", 0, <item:solarflux:sp_avaritia.infinity>, [
	[<item:avaritia:neutron>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_nugget>, <item:avaritia:infinity_catalyst>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:infinity_ingot>, <item:minecraft:air>, <item:avaritia:neutron_pile>, <item:avaritia:infinity_catalyst>, <item:solarflux:sp_avaritia.neutronium>, <item:avaritia:infinity_catalyst>, <item:avaritia:neutron_pile>, <item:minecraft:air>, <item:avaritia:infinity_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_nugget>, <item:avaritia:infinity_catalyst>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:minecraft:air>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:avaritia:neutron>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron>]
]);