<recipetype:extendedcrafting:table>.addShaped("880b4de5-fd06-43cc-88a0-a6ba4e55c5be", 0, <item:solarflux:sp_avaritia.neutronium>, [
	[<item:avaritia:neutron>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:solarflux:sp_8>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_nugget>, <item:solarflux:sp_de.draconic>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:solarflux:sp_8>, <item:avaritia:neutron>, <item:avaritia:neutron_pile>, <item:solarflux:sp_de.draconic>, <item:solarflux:sp_8>, <item:solarflux:sp_de.draconic>, <item:avaritia:neutron_pile>, <item:avaritia:neutron>, <item:solarflux:sp_8>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_nugget>, <item:solarflux:sp_de.draconic>, <item:avaritia:neutron_nugget>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_pile>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>], 
	[<item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>], 
	[<item:avaritia:neutron>, <item:minecraft:air>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:solarflux:sp_8>, <item:avaritia:neutron_ingot>, <item:avaritia:neutron_ingot>, <item:minecraft:air>, <item:avaritia:neutron>]
]);